DROP TABLE IF EXISTS book;
CREATE TABLE book(isbn VARCHAR(22) PRIMARY KEY, title VARCHAR(255) NOT NULL, quantity integer, author VARCHAR(255) NOT NULL);

DROP TABLE IF EXISTS user;
CREATE TABLE user(id SERIAL PRIMARY KEY, name VARCHAR(255) NOT NULL, token VARCHAR(255) NOT NULL);